# Generated by Django 5.2.5 on 2025-08-21 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reddit_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField(blank=True, null=True)),
                ('subreddit', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('posted', 'Posted'), ('failed', 'Failed')], default='posted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reddit_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='reddit_accounts.redditaccount')),
            ],
        ),
    ]
