# Generated by Django 5.2.5 on 2025-08-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('POSTER', 'Poster'), ('VIEWER', 'Viewer')], default='VIEWER', max_length=10),
        ),
    ]
