# Generated by Django 5.2.5 on 2025-08-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='redditaccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='redditaccount',
            name='reddit_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='redditaccount',
            name='scopes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='redditaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='redditaccount',
            name='reddit_username',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='redditaccount',
            name='refresh_token',
            field=models.CharField(max_length=512),
        ),
    ]
