# Generated by Django 5.2.5 on 2025-09-04 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_accounts', '0003_oauthstate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oauthstate',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='redditaccount',
            options={'ordering': ['-created_at'], 'verbose_name': 'Reddit Account', 'verbose_name_plural': 'Reddit Accounts'},
        ),
        migrations.AddField(
            model_name='oauthstate',
            name='app_identifier',
            field=models.CharField(default='app1', max_length=10),
        ),
        migrations.AddField(
            model_name='redditaccount',
            name='account_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='redditaccount',
            name='app_identifier',
            field=models.CharField(default='app1', help_text='Which Reddit app configuration this account uses (app1, app2, etc.)', max_length=10),
        ),
        migrations.AddField(
            model_name='redditaccount',
            name='has_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='redditaccount',
            name='karma_comment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='redditaccount',
            name='karma_link',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oauthstate',
            name='provider',
            field=models.CharField(default='reddit', max_length=20),
        ),
        migrations.AlterField(
            model_name='oauthstate',
            name='state',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='oauthstate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='redditaccount',
            name='reddit_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='redditaccount',
            name='reddit_username',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='redditaccount',
            name='refresh_token',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='redditaccount',
            name='scopes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterUniqueTogether(
            name='redditaccount',
            unique_together={('user', 'reddit_username', 'app_identifier')},
        ),
        migrations.AddIndex(
            model_name='oauthstate',
            index=models.Index(fields=['created_at'], name='reddit_acco_created_2300bd_idx'),
        ),
    ]
